name: GmodNET.Extensions.Hosting CI

env:
  RUNTIME_DOWNLOAD_LINK: https://github.com/GmodNET/runtime-nightly/releases/download/0.7.0/gmod-dot-net-linux.0.7.0.tar.gz

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  test-and-deploy:
  
    name: Test and Deploy

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.1
      
    - name: Download Steam and Install Garry's Mod Dedicated Server
      run: |
           wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
           tar -xvzf steamcmd_linux.tar.gz
           rm -rfv steamcmd_linux.tar.gz
           ./steamcmd.sh +login anonymous +force_install_dir gmod "+app_update 4020 -beta x86-64 validate" +quit
           
    - name: Build tests
      run: dotnet publish ./GmodNET.Extensions.Hosting.Tests/GmodNET.Extensions.Hosting.Tests.csproj -o ./gmod/garrysmod/lua/bin/Modules/GmodNET.Extensions.Hosting.Tests
      
    - name: Get Gmod.NET Runtime
      run: |
           wget -O runtime.tar.gz ${{ env.RUNTIME_DOWNLOAD_LINK }}
           tar xvf runtime.tar.gz
      working-directory: ./gmod/garrysmod/lua/bin/
      
    - name: Copy Lua files
      run: cp ./GmodNET.Extensions.Hosting.Tests/run_tests.lua ./gmod/garrysmod/lua/autorun
      
    - name: Run tests in Garry's Mod
      run: ./srcds_run_x64 -game garrysmod -systemtest +sv_hibernate_think 1 || true
      working-directory: ./gmod/
      timeout-minutes: 1
      
    - name: Pack nupkgs
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet pack ./GmodNET.Extensions.Hosting/GmodNET.Extensions.Hosting.csproj -c Release -o nupkgs/
      
    - name: Upload nupkgs to Azure DevOps
      if: ${{ github.event_name != 'pull_request' }}
      run: |
           dotnet nuget update source gmodnet-packages --username CI --password ${{ secrets.AZURE_DEVOPS_ARTIFACTS_PAT }} --store-password-in-clear-text
           dotnet nuget push nupkgs/**.nupkg --source gmodnet-packages --api-key az --skip-duplicate
           
    - name: Upload nupkgs to NuGet.org
      if: ${{ github.event_name == 'release' }}
      run: dotnet nuget push nupkgs/**.nupkg --source nuget --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
